<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateEquipmentsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
     public function up()
     {
       Schema::table('equipments', function (Blueprint $table) {
           $sql = "
                 CREATE TABLE equipments (
                 id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                 category_equ_id INT NOT NULL,
                 label_code_hs VARCHAR(30),
                 order_base_in_hs INT,
                 order_date_hs DATE,
                 equ_name_hf VARCHAR(100),
                 admin_name_hf VARCHAR(100),
                 use_name_hf VARCHAR(100),
                 use_base_in_hs INT NOT NULL,
                 qty_cunt_in_hs INT,
                 delete_flag_hs CHAR(1) DEFAULT '0',
                 remark_cmnt_hf VARCHAR(400)
               );
           ";
           DB::connection()->getPdo()->exec($sql);
         });

     }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('equipments');
    }
}
