<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateDeviceInfosTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
     public function up()
     {
       Schema::table('device_infos', function (Blueprint $table) {
           $sql = "
                 CREATE TABLE device_infos (
                 id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                 equipment_id INT NOT NULL,
                 model_name_hf VARCHAR(100),
                 type_code_hf VARCHAR(30),
                 serial_code_hf VARCHAR(30),
                 ip_adrs_en_hs VARCHAR(40),
                 mac_adrs_en_hs VARCHAR(40)
               );
           ";
           DB::connection()->getPdo()->exec($sql);
         });

     }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('device_infos');
    }
}
