<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateCategoryEqusTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
     public function up()
     {
       Schema::table('category_equs', function (Blueprint $table) {
           $sql = "
                 CREATE TABLE category_equs (
                 id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                 category_name_hf  VARCHAR(100)
               );
           ";
           DB::connection()->getPdo()->exec($sql);
         });

     }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('category_equs');
    }
}
