<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateUserInfosTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
     public function up()
     {
       Schema::table('user_infos', function (Blueprint $table) {
           $sql = "
                 CREATE TABLE user_infos (
                 id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                 user_code_en_hf VARCHAR(30)  NOT NULL UNIQUE,
                 password_pass_en_hf VARCHAR(30) NOT NULL,
                 user_name_hf VARCHAR(100),
                 use_base_in_hs INT,
                 admin_flag_hs CHAR(1) DEFAULT '0',
                 delete_flag_hs CHAR(1) DEFAULT '0'
               );
           ";
           DB::connection()->getPdo()->exec($sql);
         });

     }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('user_infos');
    }
}
